apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-netpol
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: todo-chatbot-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from: []
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: todo-chatbot-backend
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 7860  # Backend service port
  - to: []  # Allow other egress traffic
    ports:
    - protocol: UDP
      port: 53  # Allow DNS