apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-netpol
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: todo-chatbot-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: todo-chatbot-frontend
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  egress:
  - to: []  # Allow all egress traffic
    ports:
    - protocol: UDP
      port: 53  # Allow DNS